In [68]:
import numpy as np
import pymc3 as pm
import theano

In [48]:
a = 1
rho = np.ones(2)
nlabel = 3
k0 = 1
k1 = 1
T = []
for i in range(nlabel):
    tem = np.block([
        [np.zeros((k0 * i, k0 + k1))],
        [np.eye(k0), np.zeros((k0, k1))],
        [np.zeros((k0 * (nlabel - i - 1), k0 + k1))],
        [np.zeros((k1, k0)), np.eye(k1)]
    ])
    T.append(tem)

d = 2
Tau = np.array(list(range(4*d))).reshape((4, d))
Lambda = np.random.normal(1, 0.1, 4*d).reshape((4,d))
Lambda

array([[1.07610377, 1.0121675 ],
       [1.04438632, 1.03336743],
       [1.14940791, 0.97948417],
       [1.03130677, 0.91459043]])

In [85]:
print(np.__version__)

1.22.2


In [87]:
!pip3 install --upgrade numpy==1.20.3

  Using cached numpy-1.20.3.zip (7.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  error: subprocess-exited-with-error
  
  × Building wheel for numpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [943 lines of output]
      setup.py:66: RuntimeWarning: NumPy 1.20.3 may not yet support Python 3.10.
        warnings.warn(
      Running from numpy source directory.
      Cythonizing sources
      numpy/random/_bounded_integers.pxd.in has not changed
      numpy/random/_philox.pyx has not changed
      numpy/random/_bounded_integers.pyx.in has not changed
      numpy/random/_sfc64.pyx has not changed
      numpy/random/_mt19937.pyx has not changed
      numpy/random/bit_generator.pyx has not changed
      Processing numpy/random/_bounded_integers.pyx
      /private/var/folders/26/05snwrks4bv62vnfp9fdfhcc0000gp/T/pip-install-gneg6r7k/numpy_853174f3bd35438ca4dedf121d421c14/tool

In [83]:
len(T[0])

4

### Main


In [ ]:
# import packages and

In [ ]:
# read all parameters
jobid, nfold, nofold, seed 
d, k0, k1, nlabel, b
mu_Mu, sigma2_Mu, alpha_Lambda, beta_Lambda
nlabel, ntrace, nchain, nskip, Ntrain, Ntest


In [91]:
dg = k0 + k1 
K = ntopic = nlabel * k0 + k1

# define T
T = []
for i in range(nlabel):
    tem = np.block([
        [np.zeros((k0 * i, k0 + k1))],
        [np.eye(k0), np.zeros((k0, k1))],
        [np.zeros((k0 * (nlabel - i - 1), k0 + k1))],
        [np.zeros((k1, k0)), np.eye(k1)]
    ])
    T.append(tem)

# generate all parameters we need
np.random.seed(seed)
# dirichlet-related
alpha = np.ones(dg)
a = np.random.exponential(1 / b)



In [95]:
T

[array([[1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 1.]]),
 array([[0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 1.]]),
 array([[0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 1.]])]

In [90]:
np.random.exponential(0.1)

0.14406789664372252